Data "boldly","bravely","brightly","cheerfully","deftly","devotedly","eagerly"
Data "elegantly","faithfully","fortunately","gleefully","gracefully","happily"
Data "honestly","innocently","kindly","merrily","obediently","perfectly"
Data "politely    powerfully    safely","victoriously","warmly","vivaciously"
Data "achingly","angrily","annoyingly","anxiously","badly","boastfully"
Data "dejectedly","enviously","foolishly","hopelessly","irritably","jealously"
Data "joylessly","lazily","miserably","morosely","obnoxiously","painfully"
Data "poorly","rudely","sadly","selfishly","terribly","unhappily","wearily"
Data "audibly","deafeningly","ear-splittingly","emphatically","faintly"
Data "inaudibly","loudly","noiselessly","noisily","quietly","resonantly"
Data "resoundingly","shrilly","silently","softly","soundlessly","thunderously"
Data "uproariously","vociferously","weakly","accidentally","awkwardly","blindly"
Data "coyly","crazily","cruelly","defiantly","deliberately","doubtfully"
Data "dramatically","dutifully","enormously","excitedly","hungrily","madly"
Data "mortally","mysteriously","nervously","seriously","shakily","restlessly"
Data "solemnly","sternly","unexpectedly","wildly"